### ISSUE TITLE
Build drivers more frequently (ideally every 2 hours)

### ISSUE THREAD

**Issue by incertum** [falcosecurity/test-infra#1255]
**Motivation**

While `modern_bpf` adoption is projected to increase, many adopters appear to still rely on kernel module or traditional eBPF drivers. This statement is based on seeing Slack posts by community members saying that drivers for recent kernel releases are not yet available.

Therefore, proposing to increase the frequency of CI runs and if we were to hit budgeting limits, we can go ahead and file a ticket against the CNCF asking for an increase.

**Feature**

Run drivers build more frequently than weekly and/or occasionally manually.

Ideally: Every 2 hours.
Next Step: Daily or twice each day.

**Comment by FedeDP** [comment]
> Ideally: Every 2 hours.

Considering that today the `update-dbg` test-infra job takes more than 2hrs and the update-kernels github action in kernel-crawler takes ~40mins, we are already > 2hrs; also, the PR needs to be merged in kernel-crawler to start the automation, therefore you'd need a man (ie: me) crazily approving PRs on kernel-crawler :laughing: 
I think that daily is already good enough.

**Comment by FedeDP** [comment]
> Considering that today the update-dbg test-infra job takes more than 2hrs 

Luckily enough, the situation is going to improve once #1204 is merged since the update-dbg job will take a minute or so then :D

**Comment by FedeDP** [comment]
https://github.com/falcosecurity/kernel-crawler/pull/179 propose a daily trigger for our action.
Thoughts?
cc @maxgio92 @LucaGuerra @leogr

**Comment by leogr** [comment]
I'd start with daily updates and we will see if it is sustainable. Then we can fine tune eventually.

**Comment by maxgio92** [comment]
I agree @FedeDP

**Comment by FedeDP** [comment]
This is now closed by latest kernel-crawler and test-infra development!
Kernel-crawler will run daily, then test-infra `update-dbg` job will run a couple of hrs after the kernel-crawler one.
Kernel-crawler job will directly deploy generated jsons to github pages instead of pushing them to a long living repo, allowing us to also fix #1118 .
This way, with just a single approve (ie: the one on the PR generated by update-dbg) we will have daily drivers builds!
/close
