### ISSUE TITLE
Declarative Github teams setup

### ISSUE THREAD

**Issue by maxgio92** [falcosecurity/test-infra#405]
As @leodido proposed we should have a way to declaratively manage Github Teams (maybe with Prow), so that we can manage the truth about access control for maintainers declaratively in Git.

**Comment by leodido** [comment]
Let me expand a bit on this idea that I proposed in the falco-open-infra-maintainers.

## Problem statement

The OWNERS file declares the pool of maintainers from which @poiana chooses to ask for PR approvals and reviews for repository X.

@poiana requires that every maintainer in the OWNERS file is in the GitHub organization, but doesn't check the GitHub permissions of those maintainers.

A maintainer M needs to have GitHub "Maintain" privileges for a repository X in order to maintain it.

There is **not** an automatic and safe way to ensure that maintainer M is in the "X-maintainers" GitHub team (and not in any other), at the moment. 

The process is **manual*, error-prone, and very difficult to maintain itself. The process is **not** transparent.

## Current status

One of the GitHub organization admins create **manually** a GitHub team (conventional name: "X-maintainers") for every repository X.

Then, it adds to it the GitHub handles in the "approvers" section of the root OWNERS file of repository X.

## Temporary workaround

I propose to create a ProwJob that:

1. reads the OWNERS files (using [maintainers-generator](https://github.com/leodido/maintainers-generator) as I did for the `update-maintainers` ProwJob in the past) for every (non-archived) repository in the GitHub organization
2. obtains the people list (by querying GitHub APIs) for every GitHub team "<repo>-maintainers"
3. alerts on any GitHub team that should be missing
4. checks the set of approvers against the people list erroring out if the diff is not empty

Running this ProwJob periodically should help us spot manual errors.

## Long-term solution

Setup the GitHub teams automatically (similarly to what Kubernetes does into [org](https://github.com/kubernetes/org)).

We could use the [peribolos](https://github.com/kubernetes/test-infra/blob/master/prow/cmd/peribolos) tool for achieving this goal. In its simplest form, we'll have a new `orgs` key in the main Prow `config.yaml`.

## Resources

This [KubeCon talk](https://www.youtube.com/watch?v=te3Xj2zr1Co&ab_channel=CNCF%5BCloudNativeComputingFoundation%5D) may help.

**Comment by maxgio92** [comment]
Thank you @leodido for the detailed explanation.

Maybe is worth going with the long-term solution? I don't think the effort for having a detection cronjob is worth we'll still need prevention.

For the long-term solution I think:

## Pros

## Cons

**Comment by maxgio92** [comment]
Thank you @leodido for the detailed explanation. I'll try to be precise as you did :D

## Termporay workaround

Maybe is worth going with the long-term solution? I don't think the effort for having a detection cronjob is worth when we'll still need prevention (with enforcement).

## Long-term solution

I propose different ways other than, each one with pros and cons as I see for now:

###  [Peribolos](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos)

#### Pros
- Source of truth about _people_ (IAM for humans) **in one place** ...at least when merged in a [Prow config](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos#org-configuration) - I think we can avoid to have a dedicated [org repo](https://github.com/kubernetes/org) from where to [merge](https://github.com/kubernetes/org/tree/main/cmd/merge) the Prow configs. In the end the [admin](https://github.com/kubernetes/org/tree/main/admin) work should be the relevant part in order to deploy orgs config with [Peribolos](https://github.com/kubernetes/test-infra/tree/master/prow/cmd/peribolos#org-configuration).
- Integration with Prow

#### Cons
- Poor documentation

### IaC solutions: [Terraform](https://registry.terraform.io/providers/integrations/github/latest/docs)

#### Pros
- Github Terraform provider battle-tested
- With Terrafom we would have technology uniformity (not so relevant IMHO)
- Source of truth of infrastructure in one place
- Pretty easy

#### Cons
- Github Organizations IAM management, into two places from the point of view of Prow (`OWNERS` file is a different place)
- The state is reconciled only with push events (CD push model)

### Other IaC solutions (e.g. [Pulumi](https://www.pulumi.com/docs/intro/cloud-providers/github/))

#### Pros
- True programming (but we don't need it IMHO)

#### Cons
- One another way to declare things
- One another place where to declare things

### IaC solutions through Kubernetes API

#### Pros
- ?

#### Cons
- Risk of recursion :D
- Unneeded complexity IMHO

## The winners (for me): Peribolos and Terraform

In my opinion the most important point is to have one truth about IAM in **one place**, and with Peribolos we should achieve that.

/cc @zuc as we discussed this.

What do you think?
