### ISSUE TITLE
Build Drivers False Positive

### ISSUE THREAD

**Issue by jonahjon** [falcosecurity/test-infra#451]
**Describe the bug**

Prow build drivers job is reporting healthy on build failures

https://prow.falco.org/view/s3/falco-prow-logs/pr-logs/pull/falcosecurity_test-infra/448/build-drivers-centos-presubmit/1408049337874780160

This job from PR https://github.com/falcosecurity/test-infra/pull/448 marked as passed even though the job failed.

This leads me to believe this line in the build driver script isn't passing error up the main function since it's where the failure occured.

https://github.com/falcosecurity/test-infra/blob/master/images/build-drivers/build-drivers.sh#L76

We need to make this function pass error back to prow otherwise it just finishes the `main` function with return of `0`
 
https://github.com/falcosecurity/test-infra/blob/master/images/build-drivers/build-drivers.sh#L59

**Comment by sachinkumarsingh092** [comment]
@jonahjon if there is no issue with `patsubst` in the Makefile for the target and the substitutions are working fine, can a simple `||` condition for `exit 1` on [this line](https://github.com/falcosecurity/test-infra/blob/master/images/build-drivers/build-drivers.sh#L76) work?

**Comment by maxgio92** [comment]
I think the important motivation is that we're building drivers with a best effort approach.
There always are drivers that are not pre-built, so we potentially have driver build jobs that constantly fail.
As that said, we must (might?) go on and build what we can.

Anyway, we can reason about that, but I don't think is a matter of changing the exit code. Otherwise we won't be able to build and publish as for now, IMHO.

WDYT?
